name: Extract issue number
description: Extract issue number from the branch name of a PR merge commit
outputs:
  issue-number:
    description: 'issue number extracted'
runs:
  using: 'composite'
  steps:
    env:
      MESSAGE: ${{ github.event.commits[0].message }}
    run:  |
     export ISSUE_NUM=`echo $MESSAGE | sed -n "s/^Merge pull request \#[0-9]*.*ISSUE_\([0-9]*\).*$/\1/p"`
     echo "::set-output name=issue-number::${ISSUE_NUM}"

