name: Extract issue number
description: Extract issue number from the branch name of a PR merge commit
inputs:
  pr:
    description: "commit message to parse"
outputs:
  issue-number:
    description: 'issue number extracted'
    value: ${{ steps.parse.outputs.issue-number }}
runs:
  using: 'node16'
  main: 'dist/index.js'

