name: Extract issue number
description: Extract issue number from the branch name of a PR merge commit
inputs:
  commit-message:
    description: "commit message to parse"
outputs:
  issue-number:
    description: 'issue number extracted'
runs:
  using: 'composite'
  steps:
    run: MESSAGE=${{ inputs.commit-message }} ISSUE_NUM=`echo $MESSAGE | sed -n "s/^Merge pull request \#[0-9]*.*ISSUE_\([0-9]*\).*$/\1/p"` echo "::set-output name=issue-number::${ISSUE_NUM}"

